# Generated by Django 5.2 on 2025-07-20 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic',
            name='sale',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
