# Generated by Django 4.2.11 on 2025-07-29 04:33

from django.db import migrations, models
import utils.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0003_viewhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic',
            name='intro_image_1',
            field=models.ImageField(blank=True, null=True, upload_to=utils.helpers.get_file_path),
        ),
        migrations.AddField(
            model_name='comic',
            name='intro_image_2',
            field=models.ImageField(blank=True, null=True, upload_to=utils.helpers.get_file_path),
        ),
        migrations.AddField(
            model_name='comic',
            name='intro_image_3',
            field=models.ImageField(blank=True, null=True, upload_to=utils.helpers.get_file_path),
        ),
    ]
