# Generated by Django 4.2.11 on 2025-07-29 05:03

from django.db import migrations, models
import utils.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0004_comic_intro_image_1_comic_intro_image_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='intro_image_1',
            field=models.ImageField(blank=True, null=True, upload_to=utils.helpers.get_file_path_intro),
        ),
        migrations.AlterField(
            model_name='comic',
            name='intro_image_2',
            field=models.ImageField(blank=True, null=True, upload_to=utils.helpers.get_file_path_intro),
        ),
        migrations.AlterField(
            model_name='comic',
            name='intro_image_3',
            field=models.ImageField(blank=True, null=True, upload_to=utils.helpers.get_file_path_intro),
        ),
    ]
