# Generated by Django 5.2 on 2025-07-14 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_is_paid_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Thanh toán khi nhận hàng (COD)'), ('momo', 'Thanh toán qua Momo'), ('vnpay', 'Thanh toán qua VNPay')], default='cod', max_length=20),
        ),
    ]
