# Generated by Django 5.2 on 2025-07-15 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_payment_method'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={},
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'COD'), ('momo', 'Momo'), ('vnpay', 'VNPay')], default='cod', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ xử lý'), ('confirmed', 'Đã xác nhận'), ('preparing', 'Đang chuẩn bị hàng'), ('shipped', 'Đã giao hàng'), ('delivered', 'Giao hàng thành công'), ('cancelled', 'Đã hủy'), ('returned', 'Đã trả hàng'), ('refunded', 'Đã hoàn tiền')], default='pending', max_length=20),
        ),
    ]
