# Generated by Django 5.2 on 2025-07-15 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_options_alter_orderitem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Thanh toán bằng tiền mặt'), ('momo', 'Thanh toán qua MoMo'), ('vnpay', 'Thanh toán qua VNPay')], default='cod', max_length=20),
        ),
    ]
