# Generated by Django 4.2.11 on 2025-07-25 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_options_alter_orderitem_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Thanh toán bằng tiền mặt'), ('vnpay', 'Thanh toán qua VNPay')], default='cod', max_length=20),
        ),
    ]
