# Generated by Django 4.2.11 on 2025-07-30 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Chưa thanh toán'), ('paid', 'Đã thanh toán'), ('refunded', 'Đã hoàn tiền')], default='unpaid', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ xử lý'), ('confirmed', 'Đã xác nhận'), ('preparing', 'Đang chuẩn bị hàng'), ('shipped', 'Đã giao hàng'), ('delivered', 'Giao hàng thành công'), ('cancelled', 'Đã hủy'), ('returned', 'Đã trả hàng')], default='pending', max_length=20),
        ),
    ]
