# Generated by Django 4.2.11 on 2025-07-22 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_passwordresettoken'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passwordresettoken',
            options={'verbose_name_plural': 'Password Reset Token'},
        ),
    ]
